### ISSUE TITLE
Issue - Getting lots of dependency jar issues. Already added httpclient,httpcore jars. Do we need to add specific version of the jars

### ISSUE THREAD

**Issue by skumaridas10** [avadev/AvaTax-REST-V2-JRE-SDK#53]
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/ssl/SSLContexts
	at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:966)
	at org.apache.http.impl.client.HttpClients.createDefault(HttpClients.java:56)
	at net.avalara.avatax.rest.client.RestCall.<init>(RestCall.java:53)
	at net.avalara.avatax.rest.client.RestCall.<init>(RestCall.java:61)
	at net.avalara.avatax.rest.client.RestCallFactory.createRestCall(RestCallFactory.java:44)
	at net.avalara.avatax.rest.client.AvaTaxClient.ping(AvaTaxClient.java:12985)
	at atg.commerce.catalog.custom.AvalaraTestConncetion.main(AvalaraTestConncetion.java:22)
Caused by: java.lang.ClassNotFoundException: org.apache.http.ssl.SSLContexts
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

**Comment by skumaridas10** [comment]
Issue is resolved. Needs to use  httpcore-4.4 jar onwards.
Thx
