### ISSUE TITLE
method updateCompany() throw ClassCastException

### ISSUE THREAD

**Issue by junfengcode** [avadev/AvaTax-REST-V2-JRE-SDK#6]
hi ,
I am using the Avatax sandbox environment for sales tax calculation service access, but I am having trouble updating the company information, please help, thanks~

SDK Version：2.17.4.60
JDK Version：1.8
my code is 

> int comId = 571575;
        CompanyModel companyModel=new CompanyModel();
        companyModel.setIsDefault(true);
        companyModel.setTaxpayerIdNumber("test1234568");
        System.out.println(client.updateCompany(comId,companyModel));

the exception is

> java.lang.ClassCastException: org.apache.http.client.methods.HttpPut cannot be cast to org.apache.http.client.methods.HttpPost
        at net.avalara.avatax.rest.client.RestCall.<init>(RestCall.java:45)
	at net.avalara.avatax.rest.client.RestCall.<init>(RestCall.java:52)
	at net.avalara.avatax.rest.client.RestCall.<init>(RestCall.java:56)
	at net.avalara.avatax.rest.client.RestCallFactory.createRestCall(RestCallFactory.java:32)
	at net.avalara.avatax.rest.client.AvaTaxClient.updateCompany(AvaTaxClient.java:400)
	at com.focustech.silk.tax.avalara.test.TestCompany.update(TestCompany.java:48)

**Comment by drheart** [comment]
Hi @junfengcode, I'll get this added to the unit tests and addressed.
